Input component initial
Mystypix/grub pull request #10
Opened 2023-01-20 19:50 UTC by karfous

2023-01-20 20:34 UTC, Mystypix commented on src/components/input/input.tsx
> +  onChange: (value: string) => void; // TODO wanna know more about the syntax
Non blocking and non forcing - i like to order object, attributes, lists like this alphabetically. Its easier to find something later.

To explain the syntax - (if the comment is for me :D) its a way how to type functions. On left side, you have to pass all the argument you are actually putting there (names of the parameters doesn't have to be same as in parent component) and right side is, what you get back when callback function is called in the parent component. `Void`  means nothing...

2023-01-20 20:35 UTC, Mystypix commented on src/components/input/input.tsx
> +  value, // TODO what about some validation - for example password validation ?
Yeah, might be nice, there are packages to help with that. Good comment

2023-01-20 20:37 UTC, Mystypix commented on src/components/input/input.tsx
> +  const onChangeHandler = (e: any) => {
`any` => `SyntheticEvent`

2023-01-20 20:39 UTC, Mystypix commented on src/pages/add-recipe/add-recipe.tsx
> +          type="text"
I would say `text` is most used so i would set it as default in the `Input` component

2023-01-20 20:40 UTC, Mystypix commented on src/pages/signIn/signIn.tsx
> +        label="Your secrete password"
secrete => secret

2023-01-20 20:43 UTC, Mystypix commented on src/pages/add-recipe/add-recipe.tsx
> +          placeholder=""
Can be omitted, you don't have to specify it as blank string

2023-01-20 20:45 UTC, Mystypix commented on src/components/input/input.tsx
>    placeholder?: string;
There is a comment bellow about omitting props in the component. `?` here is to define it. If it would not be here, then you would need to add it all the time...

2023-01-21 13:58 UTC, karfous commented on src/components/input/input.tsx
> +  const onChangeHandler = (e: any) => {
I was not sure about what you meant. So I asked GPT :) But I will use SyntheticEvent because I believe you have a reason for this...

> It's important to note that the SyntheticEvent is a more general event type and it doesn't have any type information about the target element, So It's recommended to use the React.MouseEvent<T> or React.FormEvent<T> for a better type safety

2023-01-21 20:08 UTC, karfous commented
I have edited the input component and repaired some problems. 
Added:
- validator argument
Questions:
- not sure about TS checking in input.tsx onChangeHandler

2023-01-21 20:27 UTC, Mystypix commented on src/components/input/input.tsx
> +  const onChangeHandler = (e: any) => {
Ask google and typescript docs, not AI :D Anyway, yes, i will admit that typescript is really not my strong site (i'm sort of a hater, because im too dumb to fully get it). GPT is right that its generic type and we could be more specific that its an event from html input. There is a type for that... but i hate them :D

2023-01-21 20:33 UTC, Mystypix commented on src/components/input/input.tsx
> +    if (validator && !validator(e)) return; // TODO do something when it is not valid
This is sort of useless here :) validation will be part of the form, not input component. We are calling callback function on every change of input value and some validation will happen once you submit the form. If you would check my every key press, and scream at me what i should do i would kill you...

So, please remove it again :)

2023-01-21 20:36 UTC, Mystypix commented on src/components/input/input.tsx
> +    onChange(e.currentTarget.value); // BUG value property does not exist on currentTarget in ts. but it is there in browser :)
Maybe i'll learn something new too :) why do you need or want to use currentTarget anyway?

2023-01-21 20:37 UTC, Mystypix requested changes
Please remove validator prop

2023-01-22 12:14 UTC, karfous commented on src/components/input/input.tsx
> +    if (validator && !validator(e)) return; // TODO do something when it is not valid
Well when you set a password, you are somethime warned that it does not have proper length, that you did not use special characters etc. Input warns you for example by coloring background into red or showing non modal popup ... I would say that it is quite a nice way how to inform user about a problem. If you validate after submit user has to click one more time and can be confused why it is not happening what he expected.

2023-01-22 12:15 UTC, karfous commented on src/components/input/input.tsx
> +    onChange(e.currentTarget.value); // BUG value property does not exist on currentTarget in ts. but it is there in browser :)
I did not find target property but only currentTarget in synthetic event. That is why :) The explanation of using currentTarget is because of realtime validation. :)

2023-01-22 12:20 UTC, karfous commented on src/components/input/input.tsx
> +  const onChangeHandler = (e: any) => {
My questions are so basic that it would really be surprising to find out GPT is wrong :D ... I will use it because the way it explains things is super cool ! try it you will love it. Ok verify its output, but still, will save a ton of your time.

2023-01-22 12:21 UTC, karfous commented on src/components/input/input.tsx
> +    if (validator && !validator(e)) return; // TODO do something when it is not valid
Ok validation will be part of the form - we can sent validator func to the callback of input :)

2023-01-22 12:54 UTC, karfous commented
OK, another try. My idea is to sent the whole synthetic object from an input to the form where the validation will be, so I can also change the child input from outside.  I need a handler in singin and signup page, cannot easily call f.e. setEmail from input callback.

2023-01-23 20:20 UTC, Mystypix commented on src/components/input/input.tsx
> +    if (validator && !validator(e)) return; // TODO do something when it is not valid
Thats exactly what will happen. It reminds me, that we are missing error prop, but it can be added later...

2023-01-23 20:23 UTC, Mystypix commented on src/components/input/input.tsx
> +  onChange?: (event: React.ChangeEvent<HTMLInputElement>) => void;
Why did you made `onChange` optional prop? :)

2023-01-23 21:17 UTC, karfous commented on src/components/input/input.tsx
> +  onChange?: (event: React.ChangeEvent<HTMLInputElement>) => void;
Does all inputs need to have some onChange actions? Can I read their values f.e. onSubmit form with ref property ?

2023-01-24 23:19 UTC, karfous commented on src/components/input/input.tsx
> +    onChange(event.currentTarget.value);
Input will always call callback with its value. Input value is the only thing I am interested in. I hope so 👍🏻

2023-01-24 23:28 UTC, karfous commented on src/pages/sign-up/sign-up.tsx
> +          onChange={setPasswordHandler}
I have a really serious problem. After while I came back to handler which is redundat here as we discussed. But it does not make sense to me more I am thinking about it. I will call you tomorrow...

2023-01-26 07:21 UTC, Mystypix approved these changes

2023-01-26 21:00 UTC, merged