Recipe tile
Mystypix/grub pull request #13
Opened 2023-01-22 13:43 UTC by karfous

I have created first try recipe component - something like the image in [notion ](https://www.notion.so/42737dd18bc041569ac84170a12e2594?v=75b0295b4fa7491983ab6cdf39a118e0&p=b24059244dd145cebf5d536b6badeb28&pm=s) .

The component will contain two more components
- rating
- likebutton

Is should navigate to recipedetail page once clicked. The page is accesible with recipe ID from DB

2023-01-23 12:50 UTC, Mystypix commented on src/components/recipe-tile/recipe-tile.tsx
> +  isFavorite: boolean; // TODO JaKa what if unregistered user? what if registered user? the icon should change according to the fact that user liked it or not. But unregistered user does not provide
As explained on FB. It will be part of the recipeData...

2023-01-23 12:51 UTC, Mystypix commented on src/components/recipe-tile/recipe-tile.tsx
> +        <p className={css["recipe-header"]}>{recipeData.name}</p>
Does actually application works? Would expect to crush here on reading name from undefined...

2023-01-23 12:54 UTC, Mystypix commented on src/components/recipe-tile/recipe-tile.tsx
> +      className={css["recipe-tile"]}
Please, use dot notation and camelCase. Its less characters, easier to type and nicer to look :)
`css.recipeTile`. I've setup plugin so class .recipe-tile will be translated to CC

2023-01-23 13:06 UTC, Mystypix commented on src/components/recipe-tile/recipe-tile.tsx
> +      <button className={isFavorite ? css["add-to-favorite"] : ""}>Like</button>
Now is the time to introduce you `clsx` library. 
You will you it alot... 
Import it, and then use it like this
`className={clsx({[css.addToFavorite]: isFavorite})}`

Check usage of this https://github.com/lukeed/clsx

2023-01-23 13:09 UTC, Mystypix commented on src/components/recipe-tile/recipe-tile.tsx
> +      <img src="food.webp" className={css["recipe-image"]} /> // TODO binary
I see you are not even displaying or testing the component :D please, do so. This is not comment but part of the DOM...

2023-01-23 13:10 UTC, Mystypix requested changes
See the comments

2023-01-23 16:11 UTC, karfous commented on src/components/recipe-tile/recipe-tile.tsx
> +        <p className={css["recipe-header"]}>{recipeData.name}</p>
Well. I do not use the component anywhere so the app should lot crash. Or?

2023-01-23 16:12 UTC, karfous commented on src/components/recipe-tile/recipe-tile.tsx
> +      className={css["recipe-tile"]}
Ok

2023-01-23 16:12 UTC, karfous commented on src/components/recipe-tile/recipe-tile.tsx
> +      <button className={isFavorite ? css["add-to-favorite"] : ""}>Like</button>
Todo

2023-01-23 16:13 UTC, karfous commented on src/components/recipe-tile/recipe-tile.tsx
> +      <img src="food.webp" className={css["recipe-image"]} /> // TODO binary
Hoops.

2023-01-23 22:31 UTC, karfous commented
I will test the component probably tomorrow. will see how much work will be. The next pull request is just for you info.

2023-01-24 09:29 UTC, Mystypix commented on package.json
> +    "clsx": "^1.2.1",
It is already installed in develop branch. You have merge conflict because of it now :)

2023-01-24 09:30 UTC, Mystypix commented on src/components/recipe-tile/recipe-tile.module.scss
> +.recipeTile {
I personally dont mind this change, but it was un necessary :) on css side it can stay as kebab case. 
Not saying you need to change it back, just clarifying...

2023-01-24 09:31 UTC, Mystypix commented on src/components/recipe-tile/recipe-tile.tsx
> +import clsx from "clsx"; //not necessary at last
If not necessary, then don't import it :D

2023-01-24 09:32 UTC, Mystypix requested changes
Remove the import and i guess whole package. It might resolve the conflict with develop. Then its a good to go

2023-04-11 08:57 UTC, closed without merging